<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TX717-4441WGD" name="testscripts.SF.SmokeTest_API.TC_SF_API_AdminAccounts" tests="1" failures="0" timestamp="16 Jun 2017 16:52:20 GMT" time="4.359" errors="1">
  <testcase name="runTC_SF_API_AdminAccounts" time="4.359" classname="testscripts.SF.SmokeTest_API.TC_SF_API_AdminAccounts">
    <error type="com.cognizant.framework.FrameworkException" message="The test case &quot;TC_SF_API_AdminAccounts&quot; is not found in the Business Flow sheet!">
      <![CDATA[com.cognizant.framework.FrameworkException: The test case "TC_SF_API_AdminAccounts" is not found in the Business Flow sheet!
	at com.cognizant.Craft.DriverScript.initializeBusinessFlow(DriverScript.java:559)
	at com.cognizant.Craft.DriverScript.initializeTestScript(DriverScript.java:544)
	at com.cognizant.Craft.DriverScript.executeCraft(DriverScript.java:156)
	at com.cognizant.Craft.DriverScript.driveTestExecution(DriverScript.java:150)
	at testscripts.SF.SmokeTest_API.TC_SF_API_AdminAccounts.runTC_SF_API_AdminAccounts(TC_SF_API_AdminAccounts.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- runTC_SF_API_AdminAccounts -->
</testsuite> <!-- testscripts.SF.SmokeTest_API.TC_SF_API_AdminAccounts -->
